/* Patches */
#include "alpha.h"
#include "boxdraw.h"
#include "drag-n-drop.h"
#include "opencopied.h"
#include "font2.h"
#include "keyboardselect_reflow_st.h"
#include "keyboardselect_reflow_x.h"
#include "openselectedtext.h"
#include "xresources.h"
